<?php
    /*
    Author: Safiq Momin
    Date of creation: 06-01-2018
    Description: The file contains html code for registration

    Modified by: Corinne Mullan
    Date: 06-02-2018
    Description:  Modified client-side validation to use jQuery-validation.
                  Added input field hints using popovers.
                  Modified formatting to use a Bootstrap "card" layout.

    Modified by: Joshua McNabb
    Date: 06-05-2018 - 06-05-2018
    Description: Added dropdown with every country, sorted by which continent they're on
                 Added sessions that display error messages generated by the processRegistration.php page
    */
    include('../inc/global.php');

    $page = 5;

    // Store error message sessions as variables so they're not called multiple times in the script
    $firstnameError = (isset($_SESSION['firstnameError_register']) ? $_SESSION['firstnameError_register'] : NULL);
    $lastnameError = (isset($_SESSION['lastnameError_register']) ? $_SESSION['lastnameError_register'] : NULL);
    $addressError = (isset($_SESSION['addressError_register']) ? $_SESSION['addressError_register'] : NULL);
    $cityError = (isset($_SESSION['cityError_register']) ? $_SESSION['cityError_register'] : NULL);
    $provinceError = (isset($_SESSION['provinceError_register']) ? $_SESSION['provinceError_register'] : NULL);
    $postalcodeError = (isset($_SESSION['postalcodeError_register']) ? $_SESSION['postalcodeError_register'] : NULL);
    $countryError = (isset($_SESSION['countryError_register']) ? $_SESSION['countryError_register'] : NULL);
    $homephoneError = (isset($_SESSION['homephoneError_register']) ? $_SESSION['homephoneError_register'] : NULL);
    $businessphoneError = (isset($_SESSION['businessphoneError_register']) ? $_SESSION['businessphoneError_register'] : NULL);
    $emailError = (isset($_SESSION['emailError_register']) ? $_SESSION['emailError_register'] : NULL);
    $usernameError = (isset($_SESSION['usernameError_register']) ? $_SESSION['usernameError_register'] : NULL);
    $passwordError = (isset($_SESSION['passwordError_register']) ? $_SESSION['passwordError_register'] : NULL);
    $confirmError = (isset($_SESSION['confirmError_register']) ? $_SESSION['confirmError_register'] : NULL);
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Travel Experts - Create Free Account</title>
        <?php include('../inc/css.php'); ?>
        <style type="text/css">
            body{ font: 14px sans-serif; }
            .wrapper{ width: 350px; padding: 20px; }
        </style>
        <link rel="stylesheet" href="register.css" />
    </head>

    <body>
        <?php include('../inc/navigation.php'); ?>
        <div class="container" style="margin-top:80px; margin-bottom:80px;">
            <?php
                // Display how many errors are in the form
                if(isset($_SESSION['formErrors']) && $_SESSION['formErrors'] > 0)
                    echo '<div id="registrationFormError" class="notice notice-danger"><strong>Error:</strong>&nbsp; There are <u>' . $_SESSION['formErrors'] . ' errors</u> in the registration form. Please fix them before proceeding.</div>';
            ?>
            <div class="card">
                <div class="card-header"><h5>Create Free Account</h5></div>
                <div class="card-body">
                    <h5 style="margin:10px 0 15px 0;">Billing Information</h5>
                    <form id="createAccount" action="processRegistration.php" method="POST">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">First Name <font color="red">*</font></label>
                                <input type="text" class="form-control" id="firstname" name="firstname" placeholder="John"<?php if(isset($_SESSION['register_firstname'])) echo ' value="' . $_SESSION['register_firstname'] . '"'; ?> />
                                <span class="error"><?php echo (isset($firstnameError)) ? $firstnameError : ''; ?></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">Last Name <font color="red">*</font></small></label>
                                <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Doe"<?php if(isset($_SESSION['register_lastname'])) echo ' value="' . $_SESSION['register_lastname'] . '"'; ?> />
                                <span class="error"><?php echo (isset($lastnameError)) ? $lastnameError : ''; ?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address">Address</label>
                            <input type="text" class="form-control" id="address" name="address" placeholder="12345-Something ST NW"<?php if(isset($_SESSION['register_address'])) echo ' value="' . $_SESSION['register_address'] . '"'; ?> />
                            <span class="error"><?php echo (isset($addressError)) ? $addressError : ''; ?></span>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="city">City</label>
                                <input type="text" class="form-control" id="city" name="city"<?php if(isset($_SESSION['register_city'])) echo ' value="' . $_SESSION['register_city'] . '"'; ?> />
                                <span class="error"><?php echo (isset($cityError)) ? $cityError : ''; ?></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="province">Province</label>
                                <select id="province" name="province" class="form-control">
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'Choose Province' ? ' selected' : ''); ?>>Choose Province</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'AB' ? ' selected' : ''); ?>>AB</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'BC' ? ' selected' : ''); ?>>BC</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'MB' ? ' selected' : ''); ?>>MB</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'NS' ? ' selected' : ''); ?>>NS</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'NB' ? ' selected' : ''); ?>>NB</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'NL' ? ' selected' : ''); ?>>NL</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'NT' ? ' selected' : ''); ?>>NT</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'NU' ? ' selected' : ''); ?>>NU</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'ON' ? ' selected' : ''); ?>>ON</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'PE' ? ' selected' : ''); ?>>PE</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'QC' ? ' selected' : ''); ?>>QC</option>
                                    <option<?php if(isset($_SESSION['register_province'])) echo ($_SESSION['province'] == 'SK' ? ' selected' : ''); ?>>SK</option>
                                    <option>YT</option>
                                </select>
                                <span class="error"><?php echo (isset($provinceError)) ? $provinceError : ''; ?></span>
                            </div>
                            <div class="form-group col-md-2">
                                <label for="postalcode">Postal Code</label>
                                <input type="text" class="form-control" id="postalcode" name="postalcode" placeholder="N1N 1N1"<?php if(isset($_SESSION['register_postalcode'])) echo ' value="' . $_SESSION['register_postalcode'] . '"'; ?> />
                                <span class="error"><?php echo (isset($postalcodeError)) ? $postalcodeError : ''; ?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="country">Country</label>
                            <select id="country" name="country" class="form-control">
                                <?php
                                    $countries = array("Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "France Metropolitan", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard and Mc Donald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan", "Lao, People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia, The Former Yugoslav Republic of", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia (Sloirgin Islands (Britisvak Republic)", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Vh)", "Virgin Islands (U.S.)", "Wallis and Futuna Islands", "Western Sahara", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe");

                                    // Loop through all the countries, and select the one that the user entered previously if there werer other form errors
                                    foreach($countries as $name) {
                                        if($_SESSION['country'] == $name)
                                            echo "<option value=\"$name\" selected>$name</option>";
                                        else
                                            echo "<option value=\"$name\">$name</option>";
                                    }
                                ?>
                            </select>
                            <span class="error"><?php echo (isset($countryError)) ? $countryError : ''; ?></span>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="homephone">Home Phone</label>
                                <input type="tel" class="form-control" id="homephone" name="homephone"<?php if(isset($_SESSION['register_homephone'])) echo ' value="' . $_SESSION['register_homephone'] . '"'; else echo ' value=1'; ?> />
                                <span class="error"><?php echo (isset($homephoneError)) ? $homephoneError : ''; ?></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="businessphone">Business Phone</label>
                                <input type="tel" class="form-control" id="businessphone" name="businessphone"<?php if(isset($_SESSION['register_businessphone'])) echo ' value="' . $_SESSION['register_businessphone'] . '"'; else echo ' value=1'; ?> />
                                <span class="error"><?php echo (isset($businessphoneError)) ? $businessphoneError : ''; ?></span>
                            </div>
                        </div>

                        <h5 style="margin:10px 0 15px 0;">Account Information</h5>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="email">Email <font color="red">*</font></label>
                                <input type="text" class="form-control" id="email" name="email"<?php if(isset($_SESSION['register_email'])) echo ' value="' . $_SESSION['register_email'] . '"'; ?> required />
                                <span class="error"><?php echo (isset($emailError)) ? $emailError : ''; ?></span>
                            </div>

                            <div class="form-group col-md-6 <?php echo (!isset($usernameError)) ? 'has-error' : ''; ?>">
                                <label>Username <font color="red">*</font></label>
                                <input type="text" name="username" class="form-control"<?php if(isset($_SESSION['register_username'])) echo ' value="' . $_SESSION['register_username'] . '"'; ?> required />
                                <span class="error"><?php echo (isset($usernameError)) ? $usernameError : ''; ?></span>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6 <?php echo (!isset($usernameError)) ? 'has-error' : ''; ?>">
                                <label>Password <font color="red">*</font></label>
                                <input type="password" name="password" class="form-control"<?php /*if(isset($_SESSION['password'])) echo ' value="' . $_SESSION['register_password'] . '"';*/ ?> required />
                                <span class="error"><?php echo (isset($passwordError)) ? $passwordError : ''; ?></span>
                            </div>
                            <div class="form-group col-md-6 <?php echo (!isset($confirmError)) ? 'has-error' : ''; ?>">
                                <label>Confirm Password <font color="red">*</font></label>
                                <input type="password" name="confirm" class="form-control"<?php /*if(isset($_SESSION['confirm'])) echo ' value="' . $_SESSION['register_confirm'] . '"';*/ ?> required />
                                <span class="error"><?php echo (isset($confirmError)) ? $confirmError : ''; ?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-success" value="Create Account" />
                        </div>
                    </form>
                    <p>Already have an account? <a href="../login/index.php">Login here</a>.</p>
                </div>
            </div>
        </div>
    </div>

    <?php include('../inc/javascript.php'); ?>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    <script type="text/javascript" src="../js/validateRegistration.js"></script>
    <?php include('../inc/footer.php'); ?>
    </body>
</html>
<?php session_unset(); // Clear all the sessions so the errors go away when the user leaves the page ?>
